version: "3.8"

services:
  mongodb:
    image: 'mongo'
    volumes:
      - data:/data/db
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=max
    #   - MONGO_INITDB_ROOT_PASSWORD=password
    env_file:
      - ./env/mongo.env


volumes:
  data:
